language: node_js
node_js: "9"

install:
  npm install

script:
  - npx ganache-cli --hardfork istanbul --port 7545 --mnemonic 'amused glory pen avocado toilet dragon entry kitchen cliff retreat canyon danger' &
  - npm test

before_deploy:
  - npm run compile
deploy:
  provider: releases
  api_key: "$GIT_RELEASES_API_KEY"
  file_glob: true
  file: build/contracts/*
  skip_cleanup: true
  on:
    tags: true
